---
# tasks file for ansible-role-common

# -------------
# Variables
# -------------
- name: Include OS system variables.
  include_vars: "{{ ansible_system }}.yml"

# -------------
# Setup
# -------------
- include: setup-brew.yml
  when:  ansible_system == 'Darwin'

- include: setup-apt.yml
  when:  ansible_pkg_mgr == 'apt'

# -------------
# Configuration
# -------------
- include: config-bash.yml

- include: config-byobu.yml

- include: config-vim.yml
