---
# tasks file for ansible-role-common

# -------------
# Platform conditional install and configuration
# -------------
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: setup-Darwin.yml
  when:  ansible_os_family == 'Darwin'

- include: setup-Debian.yml
  when:  ansible_os_family == 'Debian'

