---
# tasks file for ansible-role-common

# -------------
# Variables
# -------------
- name: main   |  incl | include OS system variables.
  include_vars: "{{ ansible_system }}.yml"

# -------------
# Setup
# -------------
- name: setup  |  brew | ensure non-OS common packages present
  homebrew: name="{{ item }}"
  with_items: __common_packages
  when:  ansible_system == 'Darwin'

- name: setup  |   apt | ensure common packages present
  sudo: Yes
  apt: name="{{ item }}" update_cache=Yes cache_valid_time=86400
  with_items: __common_packages
  when:  ansible_pkg_mgr == 'apt'

# -------------
# Configuration
# -------------
- include: config-bash.yml

- include: config-byobu.yml

- include: config-vim.yml
