---
# Darwin (Mac OS X) tasks file for ansible-role-common

# -------------
# Install and configure common packages
# -------------
- name: Darwin | ensure non-OS common packages present
  sudo: No
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: __common_packages
