---
# Debian (Linux) tasks file for ansible-role-common

# -------------
# Install and configure common packages
# -------------
- name: setup  |   apt | ensure common packages present
  sudo: Yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: Yes
    cache_valid_time: 86400
  with_items: __common_packages
