---
# Debian (Linux) tasks file for ansible-role-common

# -------------
# Install and configure terminal applications
# -------------
- name: Debian | ensure common packages present
  sudo: Yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: Yes
    cache_valid_time: 86400
  with_items:
    - "{{ common_packages_file }}"
    - "{{ common_packages_network }}"
    - "{{ common_packages_terminal }}"
